### ISSUE TITLE
Citation format

### ISSUE THREAD

**Issue by tristaaan** [diegocasmo/ml-project#12]
Is it 

```tex
... we discovered amazing things \cite{us}.
```
or
```tex
... we discovered amazing things. \cite{us}
```
(difference of placement period)

**Comment by tristaaan** [comment]
Additionally, should we be using `\cite{me}` or `~\cite{me}`

**Comment by tristaaan** [comment]
I observe papers predominantly using the former. **`...something incredible \cite{them} •`** 

The `~` is a [non-breaking space](https://en.wikibooks.org/wiki/LaTeX/Text_Formatting#Non-breaking_spaces) I don't know how important it is for us yet.

**Comment by diegocasmo** [comment]
This issue has already been solved.
