### ISSUE TITLE
Better data splitting.

### ISSUE THREAD

**Issue by tristaaan** [diegocasmo/ml-project#26]
```py
train = df.sample(frac=0.95) 
valid = df.sample(frac=0.05)
```

This works well but it could exclude some images entirely and there is probably some overlap between the two. Better way might be to 

```py
df = df.sample(frac=1)  # shuffle
frac1 = int(df.rows * 0.95)
train = df[0:frac1]
valid = df[frac1:]
```

**Comment by ankurshukla03** [comment]
> This works well but it could exclude some images entirely and there is probably some overlap between the two. 

Nice Finding.
