### ISSUE TITLE
Table layout fix

### ISSUE THREAD

**Issue by tristaaan** [diegocasmo/ml-project#37]
Takes up too much space. Here I'm wrapping it and it looks better, opening this issue for feedback. Will be pushed in #35 
.
<img width="463" alt="screen shot 2018-05-26 at 4 09 17 pm" src="https://user-images.githubusercontent.com/5470619/40577041-57bdabea-60ff-11e8-94a9-ecb8075ce3e3.png">

**Comment by ankurshukla03** [comment]
It looks much better than before. The space around table doesn't look that odd.
