### ISSUE TITLE
Report's Conclusion Section

### ISSUE THREAD

**Issue by tristaaan** [diegocasmo/ml-project#40]
- The winning kaggler and their solution, what we could take from it which would improve our network
- Why wasn't augmentation the silver bullet (I mention this in the results, I think it's on track but it could be fleshed out here and maybe backed up with something)
- Further work
  - other SDSS datasets? 
  - other astronomical tasks (see Hubble, VLA, upcoming Webb)

**Comment by diegocasmo** [comment]
In addition to what Tristan mentioned above, please make sure this section covers:

- [x] Summary of methodology (what we did)
- [x] Summarize your contributions
- [x] Further work
