### ISSUE TITLE
Report's Abstract

### ISSUE THREAD

**Issue by diegocasmo** [diegocasmo/ml-project#41]
As suggested by Gustaf, the report should contain an abstract. Based on Olle's scientific writing presentation, an abstract is a single paragraph of 100-200 words with four parts:

- [x] What's the problem?
- [x] How did you solve it?
- [x] What are the results?
- [x] Conclusion (what it means for the future)

Additional notes: no reference tags, avoid acronyms

**Comment by diegocasmo** [comment]
@ankurshukla03 wait until @tristaaan is done with #40 before working on this one.

**Comment by tristaaan** [comment]
closed with #43
