### ISSUE TITLE
Introduction and data reading

### ISSUE THREAD

**Issue by diegocasmo** [diegocasmo/ml-project#5]
+ introduction
+ data section
+ data pre-processing

(See more details in #8)

**Comment by ankurshukla03** [comment]
+ introdcution
 - [ ] approach choosed by us for solving the problem(later on not on first draft)

**Comment by diegocasmo** [comment]
> data augmentation(translation,rotation,shifting)

I thought about this as well, but I think this will be better suited when we talk about regularization, since those techniques are applied to avoid over-fitting. See [paper outline](https://github.com/diegocasmo/ml-project/blob/master/journal/23-05-2018-report-outline.md). @ankurshukla03

**Comment by ankurshukla03** [comment]
yeah you are right it should come after we have designed our model.
